### ISSUE TITLE
Confused?

### ISSUE THREAD

**Issue by turtiustrek** [bitbank2/BB-CP#2]
How can i install this?

**Comment by bitbank2** [comment]
There's nothing to install. You simply build and run it. It's a user level program that you can run from the command line. When you want it to stop, just press ENTER.

**Comment by turtiustrek** [comment]
@bitbank2 i didn't put my question right. I need to know how to use it i mean does it need the following command before the execution of the code  because i could not get it to work
it works(black with backlight) with this:sudo modporbe fbtft_device name=adafruit22a rotate=270 speed=48000000 fps=50 debug=32

but stays black/no back light  when i run your code with configured pins 

https://www.ebay.com/itm/LCD-Touch-Panel-240x320-2-4-SPI-TFT-Serial-Port-Module-With-PBC-ILI9341-5V-3-3V/291346921118?_trkparms=aid%3D555017%26algo%3DPL.CASSINI%26ao%3D1%26asc%3D20180214111925%26meid%3D49abffa5488d48549b4cfb5052d87c7a%26pid%3D100505%26rk%3D1%26rkt%3D1%26%26itm%3D291346921118&_trksid=p2045573.c100505.m3226

**Comment by hex007** [comment]
You need to not use fbtft. They are for the same purpose. To use this do the following.

1) Clone Spi_lcd repository.
2) Edit spi_lcd.c file to enable headers of the lcd you are using
3) Run make for SPI_LCD project
4) clone bb-cp repository. 
5) make project
6.1) if you have fbtft running disable it using modprobe
6.2)  run bb-cp with proper parameters

That should get you with output.

@bitbank2  it might be useful to add make flags that do the header enabling based on model. 'make ili9341' would be easier for general users to use rather than messing with headers for spi_lcd

**Comment by turtiustrek** [comment]
Hello thanks for the response but i still cannot get that darn thing to work !
the display stays white . I have connected the D/C pin too GPIO 24 (pin 18) ,rest to 3.3V,led 3.3V 
yes it also stays white when i connect REST to 22 and D/C to 18 ;-;
nothing happens but on same pin config fbtft works 
to make my life easier what are the *actual* pins used?

```
pi@retropie:/boot/disp$ sudo ./bbcp --spi_bus 0 spi_freq 46000000 --flip

Perf test: worst case framerate = 10 FPS
<25FPS indicates there is something not configured correctly with your SW/HW
Press ENTER to quit
```
right after the execution of the code i see the screen go grey for a microsecond then it turns back to White 
Thanks,
